# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '15.0'
workspace 'ClassifySound.xcworkspace'

target 'ClassifySound' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClassifySound
  pod 'Firebase', '>= 9.6.0'
  pod 'FirebaseAnalytics'
  pod 'Firebase/Database'
end
